=== adogomz/ejemplos-lenguaje-marcas/Ejercicios XSLT/Ejercicio903c.dtd
<!ELEMENT ciudades (ciudad+)> 
<!ELEMENT ciudad (pais,museo)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT museo (#PCDATA)>
	 <!ATTLIST ciudad nombre NMTOKEN #REQUIRED>

=== adogomz/ejemplos-lenguaje-marcas/Ejercicios XSLT/Ejercicio903c.xml
<?xml version="1.0" encoding="UTF-8"?>

      <!DOCTYPE ciudades SYSTEM "Ejercicio903c.dtd">
    
<ciudades>

<ciudad nombre="Madrid"><pais>España</pais><museo>Museo del Prado</museo></ciudad>

<ciudad nombre="Londres"><pais>Reino Unido</pais><museo>British Museum</museo></ciudad>

<ciudad nombre="Londres"><pais>Reino Unido</pais><museo>National Gallery</museo></ciudad>

</ciudades>
