=== adogomz/ejemplos-lenguaje-marcas/Ejercicios XSLT/Ejercicio903d.dtd
<!ELEMENT paises (pais+)> 
<!ELEMENT pais (ciudad)>
<!ELEMENT ciudad (museo)>
<!ELEMENT museo EMPTY>
	 <!ATTLIST pais nombre NMTOKENS #REQUIRED> 
	 <!ATTLIST ciudad nombre NMTOKEN #REQUIRED> 
	 <!ATTLIST museo nombre NMTOKENS #REQUIRED>

=== adogomz/ejemplos-lenguaje-marcas/Ejercicios XSLT/Ejercicio903d.xml
<?xml version="1.0" encoding="UTF-8"?>

      <!DOCTYPE paises SYSTEM "Ejercicio903d.dtd">
    
<paises>

<pais nombre="España"><ciudad nombre="Madrid"><museo nombre="Museo del Prado"/></ciudad></pais>

<pais nombre="Reino Unido"><ciudad nombre="Londres"><museo nombre="British Museum"/></ciudad></pais>

<pais nombre="Reino Unido"><ciudad nombre="Londres"><museo nombre="National Gallery"/></ciudad></pais>

</paises>
